services:
  - type: web
    name: monopoly-api
    runtime: docker
    repo: https://github.com/AlexanderZhigalskiy/monopoly-server.git
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monopoly-db
          property: connectionString
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true